### PR TITLE
Feature/dynamic trajectory

### PR DESCRIPTION
**Pull request by caksland**
I added the DynamicTrajectory object to the toolbox and added a demo of a working problem (Demo->MultiPhase).
Because phases are automatically added to the trajectory, we no longer have direct access to the phases in the main script. Instead I added a bunch of custom `add_phase_XXX` and `set_phase_XXX_options` methods to the class to provide the granular control for the phases. I think it works well, but I'd be happy if you had a better solution.
I also added a better plotting function to the Demo folder... but maybe we want to add that to shared functions?
The code can probably be cleaned up some, but for now I think it works well.
Please pull the update down and run the demo to make sure it works. The commits should be well commented too if you want to read through the changes.

### CODE REVIEW

**Comment by renkert2** [comment]
Hey Chris, 

Would it work to just hand DynamicTrajectory a list of DynamicPhases instead of the number of phases?  that way we would still have access to the phases outside of the trajectory and we wouldn't have to pass nearly as much through the DynamicTrajectory constructor.

**Comment by renkert2** [comment]
We could work with DynamicPhases a little bit so that it is easier to initialize groups of phases with similar variables.

**Comment by caksland** [comment]
I had thought of that, but it seemed kind of clunky. If all phases have the same ode, states, controls, etc, it's more compact and easy to just initialize just one phase and copy and paste it multiple times. However, I tested copying and deep copying, and that did not work. So I ended up creating DynamicTrajectory to be a 'wrapper' that creates each phase in a for-loop and links them together. If you compare Demo->MultiModel_Dymos (which uses just phases) to Demo->MultiModel (which uses DynamicTrajectory), I think it's apparent that the DynamicTrajectory code is more compact. 

I would be open to thoughts about how DynamicPhase could be improved. 

Also, if you need more customizable trajectory, then I don't think you would need DynamicTrajectory at that point anyways. See Demo->MultiModel_Dymos which is similar to what you've proposed. In the scope of dymos, the trajectory object doesn't really do much aside from linkage constraints for multiple phases.

Thoughts? I'm available to discuss next week too.

**Comment by renkert2** [comment]
I do agree that the current implementation is more compact.  At this point I'm leaning towards having an option in the phase constructor to construct identical phases, or at least something that makes it possible to easily duplicate phases.  Searching around on the web for the most pythonic way to use polymorphism, everyone points back to the for loop.  For example,

```
phases = dm.DynamicPhase(..., copies = 5)

% Modify all phases
for phase in phases:
    phase.init_vars(...)
    % anything else common to each phase

% Modify individual phases
for i in (0,1):
    phases[i].add_state(...)

% Pass to trajectory
traj = dm.DynamicTrajectory(phases, ...)
traj.init_vars(... ) % Works the same as before
```

I did run into a bug when running the  DEMOs:
 ```
 add_parameter() missing 1 required positional argument: 'units'
 ```
Is that something that's changed in the most recent version?

**Comment by caksland** [comment]
Yeah. I can give that a go... It'd essentially move the for loop in the DynamicTrajectory constructor into the DynamicPhase constructor. right? Should be easy enough. I'll let you know when that's prepared.
Also, I think that is a Dymos error. In my previous version, it required that parameter's had units defined. My try updating?

**Comment by renkert2** [comment]
Sounds good - we can chat about it Monday too. I might be missing something.  

I'll update dymos and give it another shot.

**Comment by renkert2** [comment]
Just updated Dymos to 1.4 and everything worked great!

**Review by renkert2 — APPROVED** [review]

**Comment by caksland** [comment]
I haven't changed anything on this yet.  I'm going to hold off on the merge until I test the functionality your proposed... unless you no longer think that's a good idea.

**Comment by caksland** [comment]
Yeah. I'll be in shortly. I got sidetracked with some other functionality this morning...

**Comment by caksland** [comment]
I was just looking through this. How did you get the deepcopy to work? I had tried that and it would throw me any error. Was the trick to deepcopy the options as well?
 
```
 def duplicate(self, N):
        selves = [self]
        for i in range(N - 1):
            self_copy = copy.deepcopy(self) # Make a deep copy of the phase
            self_copy.Metadata = self.Metadata # Each phase can use the same metadata object
            self_copy.options._dict = copy.deepcopy(self.options._dict) # For some reason this wasn't working
            selves.append(self_copy)
        return selves
```

**Comment by renkert2** [comment]
Yeah for some reason their OptionsDictionary object went all haywire when you try to deepcopy it. It threw away some of the options that were declared. I took a look inside the OptionsDictionary and the _dict attribute is a normal dictionary that stores all the data. Manually replacing the _dict attribute seems to do the trick.

We should definitely mark this code as a first place to start looking if the phases start acting weird; it’s kinda hard to tell how the dymos stuff will behave when it’s copied.

It might be more efficient to make shallow copies of the phases and only deepcopy the things that need it. For example, the Metadata object should be the same for each copy. But that’s probably a minor detail.

Philip Renkert

________________________________

**Pull request merged**
