### PR TITLE
Feature/dymos multi model

### PR DESCRIPTION
**Pull request by renkert2**
Support for using multiple DynamicModel models in a Group that calculates the state derivatives for a Dymos Phase.  See the PlanarQuadrotor and MM_MultiModel demos for more info.

### CODE REVIEW

**Comment by caksland** [comment]
1. I'm having a bunch of trouble getting the quadrotor optimization to run from the correct file path. The path changes, then goes to import something, changes again, and then can't find the correct files. Could you try closing Spyder, reopen the quadrotor optimization, and then try running everything?
2. I want to get the thermal system working before accepting the pull request. I'll work on that right now.

**Comment by caksland** [comment]
I completed my DEMO. Please check it: DEMO/MM_MultiModel.
When you have the chance, let me know when the Planar quadrotor is fixed. Then I can test.

**Comment by renkert2** [comment]
The new MM_MultiModel demo works great!  I added a little documentation to the and send the generated N2 files and whatnot to a subfolder.  

I can't seem to replicate the file path issues you're having on your end.  Everything should be relative to the current location of the demo file, which on my end is ./DEMO/PlanarQuadrotor/.  The models are in ./TEST_SYSTEM/PlanarQuadrotor.  What python version are you on again?  It may be an issue with using relative imports using the dot notation.  

If we want to get away from navigating relative to the current file, we could add a Windows environment variable that stores the path of the home directory.  We could then make everything relative to the value of that environment variable.  Just a thought.

**Comment by caksland** [comment]
Thanks for adding the comments. I'll pull it down and check the comments and add my own.

> What python version are you on again?
I'm on Python 3.8.8.

> we could add a Windows environment variable that stores the path of the home directory
I think that's a good idea. I think my AFRL contacts set up another repo for me with that functionality. That way we can do `import AGILe as ag`.

> Whoops just found the problem. My bad...
What problem?

**Comment by renkert2** [comment]
> What problem?
I had hard-coded file paths in one of my model documents.  It should work now.

**Comment by caksland** [comment]
I fixed another path connection. All demos are working on my end :) Can you make sure it still works for you?
Also, your quadrotor optimization completed, but the optimized and simulated trajectory do not match.
**Go ahead and merge the pull request whenever you're ready**

**Comment by renkert2** [comment]
Just merged.

**Pull request merged**
