### PR TITLE
Feature/graph model

### PR DESCRIPTION
**Pull request by caksland**
Okay. The last pull request was incomplete. That's my bad. This one is up-to-date. I've copied previous discussion points below.

Phil:
**In Convert, it may be beneficial to use something other than "" for the descriptions since this is treated as an escape character is lots of other languages. Pretty low priority but just a thought.**
**Main_AE**
It would be great to get the DAEMOT package stuff out of here at some point.
- If the algebraic solution is provided, you have an ODE. I think it's better this way.
-- Sounds good. We could have a method in DAEs that solve for the algebraic states and export as ODEs.
- I added some other 'main_' scripts to test the construction of some other simple types of models. Might be a good idea to set these up as 'unittests' if we care? Run these to build other model types.
-- Yes this wouldn't be a bad idea. Automate all the things :)
- I added options to the GraphModel conversion process. I think we should make an options package for the toolbox. Currently, our +option folders are in two separate places. We can probably do something to merge the two.
-- I agree, but I don't see the new options in this pull request. Did you add those after submitting the request, or am I missing something?
- It may be a good idea to combine Graph and GraphModel at some point. I feel like the separate classes are kind of clunky?
-- At this point yes, so long as the overhead to Graph is kept at a minimum.
- We should fix SymParam at some point.
-- I'll get on this as soon as I wrap up the Dymos stuff :).

Chris:

- What do you mean by ""? Are you saying we should move away from strings and move to characters?
- We can delete DAEMOT whenever. Interfacing with simulink models can be for another day.
- Yes, we could also include that in the DAE or AE model. It might be better there too? I'll think about moving that code over.
- None.
- Weird, they are not there on my side either. I have no clue why they didn't push. Were you able to run the code? Did you have to do anything special to push your +options folder? **(Fixed now)**
- I'll have to think a little bit more about what this would look like though because yes, I don't want to add unnecessary overhead.
- Sweet!

### CODE REVIEW

**Comment by renkert2** [comment]
> * What do you mean by ""? Are you saying we should move away from strings and move to characters?
- Haha too ironic.  I typed a backslash and it got escaped out.  It's great to avoid backslashes in general.  
> * We can delete DAEMOT whenever. Interfacing with simulink models can be for another day.
- Sounds good.  I have a pretty good method for interfacing models with Simulink but it **heavily** relies on interpreted MATLAB functions.  
> * Yes, we could also include that in the DAE or AE model. It might be better there too? I'll think about moving that code over.
- Yep that's what I was thinking
> * Weird, they are not there on my side either. I have no clue why they didn't push. Were you able to run the code? Did you have to do anything special to push your +options folder? **(Fixed now)**
- Cool.  I don't remember having to do anything special.

**Review by renkert2 — COMMENTED** [review]
Bug in plot.LabelDisturbances - DisturbanceDescriptions is no longer a property.  

Options classes probably don't need to be handles.

**Comment by caksland** [comment]
Colon is updated. I will push.
- There is no function called label disturbances in plot. I changed the name to LabelExternals. Is that not showing up on your end? It looks correct on Github.
- The options class is not a handle. TBH, I didn't look into them much so there is probably other room for improvement.
- Fixed a bug in solving for algebraic states.

Merge when you think it's good.

**Comment by renkert2** [comment]
There is no function called label disturbances in plot. I changed the name to LabelExternals. Is that not showing up on your end? It looks correct on Github.
- Gotcha.  I must have been on an older version.  
We're good to go ahead.  I'll organize the other options in the next pull request.

**Pull request merged**
