### PR TITLE
Feature/extrinsic params

### PR DESCRIPTION
**Pull request by renkert2**
Adding ExtrinsicParams feature to AGILe.  Useful for aggregating some system properties like mass and cost from the component level to the system level.

### CODE REVIEW

**Comment by caksland** [comment]
The demo ran well and this looks good to me.
2 comments. 
It looks like you're trying to merge into master. Could you change that to develop. That should clean up the commit history for this PR.
Also, could you add an feature for adding extrinsic params to the graph combination code?

**Comment by renkert2** [comment]
Sorry you weren't supposed to see this quite yet.  I though a draft pull request was kept private but I guess not.  

Just fixed the base and added the extrinsicParam stuff into SystemElement.  There's an example of that in the Demo now too.

**Comment by caksland** [comment]
I made an edit to add clear all to the header in the demo (see my commit). Otherwise, it looks good.

Side note:
the line `Sys.Params.update()` in the demo doesn't need to be called right? It's just filling in default values?

**Comment by renkert2** [comment]
Right on, thanks

The `Sys.Params.update()` line needs to be called so that we can see the correct values of the Dependent Params and extrinsicParams in the table.  Otherwise they would show up as NaN because they hadn't been calculated yet.

**Pull request merged**
