### PR TITLE
Bug/graph model sym var export

### PR DESCRIPTION
**Pull request by renkert2**
Added set method to SymVar.N so that the number of elements could be modified.  Changed GraphModel.Convert so that it doesn't regenerate symvar objects to change their number of elements.

### CODE REVIEW

**Comment by caksland** [comment]
One significant issue. 
In convert, you made it so we don't have to regenerate the SymVars, which is good. 
However, in main_UAV, we set the conversion options to solve for the algebraic states. Therefore, the DAEDesignSymVars need to become ODEDesignSymVars in the Convert function. Is there an easy way to convert between the two?

**Comment by renkert2** [comment]
Oh shoot totally overlooked that.  One sec.

**Comment by renkert2** [comment]
K I think I just fixed it - the main_UAV runs well now.  I made quite a few changes to the SymVars constructors if you wanna check it out.

**Comment by caksland** [comment]
Cool. Everything ran well from my end, so looks good to me. I'll merge into develop.

**Pull request merged**
