### PR TITLE
Feature/dymos sub index

### PR DESCRIPTION
**Pull request by caksland**
I added sub-indexing to DynamicPhase.init_vars,, fixed some bugs, and cleaned up some of the code by created additional helper functions for the Dynamic Model. Everything works well for both my Aircraft model and the Brachistochrone model.
For init_vars, I found integrating the wild card operator '*' to be to tedious and clumsy. Instead, I added an additional conditional to the add_(state/control/parameter) function calls. Way easier, but less fancy.

If you want to quickly review, I separated my commits by fixes. The commit message should be descriptive enough.
Let me know when I can merge.

### CODE REVIEW

**Comment by renkert2** [comment]
>> Way easier, but less fancy.
:)

>> For the indexing code, was this all you had to change?
`if (var in state_names) or (target in state_names):`

**Comment by caksland** [comment]
Yep, That was all I changed.
> For the indexing code, was this all you had to change?
`if (var in state_names) or (target in state_names):`

We need this incase the DynamicModel doesn't promote all the variable names. In the current implementation, DynamicModel promotes everything so it's useless. However, if we have multiple models being added to a dynamic phase, it may be more useful.
Also you wrote that code. It seems like you answered your own question :)
> Why do we need this again?

**Comment by renkert2** [comment]
Did I write that comment??? 😂

Philip Renkert

________________________________

**Comment by caksland** [comment]
I think so...

**Pull request merged**
