### PR TITLE
Feature/reduced mdao modle

### PR DESCRIPTION
**Pull request by caksland**
This PR improved the exporting functionality. It:
1) Made the model export code significantly more efficient (almost 10x faster for some test cases).
2) Updated the OpenMDAO models so that unused inputs are not added to the model.

To test the model export functionality, I would recommend running main.m, Brachistochrone_ODE.m (in OpenMDAO\Test_System\Brachistochrone) or MassSpringDamper.m (OpenMDAO\TEST_SYSTEM\MassSpringDamper).

To test the OpenMDAO functionality, I would run the Brachistochrone or MultiPhase Demos in OpenMDAO\DEMO. You can also run PyModel.py in OpenMDAO\TEST_SYSTEM\TMS. The other demos do not work because I couldn't rebuild the models to include the new function metadata (The files necessary to generate those models are not in the tool).

Let me know if you have any questions.

### CODE REVIEW

**Comment by renkert2** [comment]
Wow this feels noticeably faster!  Nice work :).  

Noticed something odd in the model export() function. 
Here's `f.py` output for the MassSpringDamper:
```
from numpy import *

def f(x,u,d,theta):
# auto-generated function from matlab

	x1=x[0]
	x2=x[1]
	
	out1 = + u1 - theta2*x1 - theta3*x2)/thet
	out2 = + u1 - theta2*x1 - theta3*x2)/thet
	
	return out1, out2
```

And here's the output from Brachistochrone:
```
from numpy import *

def f(x,u,d,theta):
# auto-generated function from matlab

	x1=x[0]
	x2=x[1]
	x3=x[2]
	u1=u[0]
	theta1=theta[0]
	
	out1 = 1); -x3*cos(u1); theta1*cos(u
	out2 = 1); -x3*cos(u1); theta1*cos(u
	out3 = 1); -x3*cos(u1); theta1*cos(u
	
	return out1, out2, out3
```

Does this happen on your end?

**Comment by caksland** [comment]
Uh... nope: I get. Sounds like a weird debugging day is in our future... let me check the versioning on functions in write_py.

```
from numpy import *

def f(x,u,d,theta):
# auto-generated function from matlab

	x1=x[0]
	x2=x[1]
	u1=u[0]
	d1=d[0]
	theta1=theta[0]
	theta2=theta[1]
	theta3=theta[2]
	
	out1 = x2
	out2 = (d1 + u1 - theta2*x1 - theta3*x2)/theta1
	
	return out1, out2
```



```
from numpy import *

def f(x,u,d,theta):
# auto-generated function from matlab

	x1=x[0]
	x2=x[1]
	x3=x[2]
	u1=u[0]
	theta1=theta[0]
	
	out1 = x3*sin(u1)
	out2 = -x3*cos(u1)
	out3 = theta1*cos(u1)
	
	return out1, out2, out3

```

**Comment by caksland** [comment]
So I cannot replicate the error. And looking at the matlab docs, none of the functions I called had version changes. We'll probably have to debug this together...? Let me know when you're available.

**Comment by caksland** [comment]
Can you check to make sure everything works now?

**Comment by renkert2** [comment]
There was a tiny typo in my_sym2char, but I fixed it and it works great now.  Thanks a bunch. Good to merge whenever.

**Review by renkert2 — APPROVED** [review]

**Pull request merged**
